# Default values for equiz.
# NOTE:
#   - '+' and '<' are special keys used by the template function equiz.parse to include other templates. E.g.,
#       - a: b                             - a: b
#         +: c                               { content of template named "c" }
#         d: e                               d: e     
#       - <: f                             { content of template named "f"}   
#   - See templates/_helpers.tpl for the definitions.

# Dependencies among different apps
# nginx
# ├── phpfpm
# │   └── phpfpminit
# │       └── html
# └── mariadb

# Settings for the php-fpm engine required to setup and run moodle
phpfpm:
  # TODO: change to support release name
  # - turn etc files to use template
  fullnameOverride: phpfpm
  # php-fpm docker image build for equiz (TODO: link to instructions on building the image)
  image:
    repository: chungc/equiz_phpfpm   # TODO: change to public registry
    tag: latest                                         # TODO: follow subchart version instead
    pullPolicy: Always # TODO: Use default value IfNotPresent
  # Setup moodle
  initContainers:
    - +: "equiz.html.init"              # initialize the moodle code folder
    - +: "equiz.phpfpm.init"            # install moodle and moodle plugins
  volumeMounts:
    - <: "equiz.phpfpm.volumeMounts"    # mount configuration files and moodle folders
  volumes:
    - +: "equiz.etc"
    - +: "equiz.html"
    - +: "equiz.moodledata"
  envFrom:
    - +: "equiz.phpfpminit.env"         # LTI patch needs WWWROOT
  livenessProbe:
    tcpSocket:
      port: phpfpm
    initialDelaySeconds: 15
  readinessProbe:
    tcpSocket:
      port: phpfpm

# Settings for mariadb for the moodle database
mariadb:
  fullnameOverride: "mariadb"
  image: 
    repository: mariadb
    tag: 10.8.4
  volumeMounts:
    - name: etc
      mountPath: /etc/mysql/my.cnf
      subPath: my.cnf
    - name: mysql
      mountPath: /var/lib/mysql
  volumes:
    - name: etc 
      +: "equiz.etc"
    - name: mysql 
      +: "equiz.mysql"
  envFrom:
    - +: "equiz.mariadb.env"
    - +: "equiz.mariadb.secret"
  livenessProbe:
    exec:
      command: ["sh", "-c", "mysqladmin status -uroot -p${MYSQL_ROOT_PASSWORD}"]
    initialDelaySeconds: 120
    timeoutSeconds: 5
    periodSeconds: 60
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    exec:
      command: ["sh", "-c", "mysqladmin status -uroot -p${MYSQL_ROOT_PASSWORD}"]
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 20

nginx:
  image: 
    repository: nginx
    tag: 1.25-alpine3.17
  volumeMounts:
    - name: etc
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: etc
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: nginx-site.conf
    - name: html
      mountPath: /var/www/html
    - name: html
      mountPath: /var/www/moodledata
  volumes:
    - name: etc 
      +: "equiz.etc"
    - name: html 
      +: "equiz.html"
    - name: moodledata 
      +: "equiz.moodledata"
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 50
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 50

# Settings for the jobe server for coderunner
redis:
  enabled: false
  fullnameOverride: "redis"
  image: 
    repository: redis
    tag: 7.0.11-alpine3.18
  volumeMounts:
    - name: etc
      mountPath: "/usr/local/etc/redis/redis.conf"
      subPath: "redis.conf"
  volumes:
    - name: etc 
      +: "equiz.etc"
  livenessProbe:
    exec:
      command: 
        - redis-cli
        - ping
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 50
  readinessProbe:
    exec:
      command: 
        - redis-cli
        - ping
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 50

# Settings for the jobe server for coderunner
jobe:
  enabled: false
  fullnameOverride: "jobe"
  image: 
    repository: trampgeek/jobeinabox
    tag: latest
  volumeMounts:
    - name: etc
      mountPath: "/var/www/html/jobe/application/config/config.php"
      subPath: "config.php"
  volumes:
    - name: etc 
      +: "equiz.etc"
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 50
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 50

# Setting for goemaxima
goemaxima:
  enabled: false
  fullnameOverride: "goemaxima"
  image:
    repository: mathinstitut/goemaxima
    tag: 2023102700-1.1.9
  volumeMounts:
    - name: html
      mountPath: "/stackmaxima"
      subPath: "question/type/stack/stack/maxima"
  volumes:
    - name: html 
      +: "equiz.html"
  envFrom:
    - +: "equiz.goemaxima.env"
  livenessProbe:
    httpGet:
      path: /goemaxima/
      port: http
    initialDelaySeconds: 30
    periodSeconds: 60
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /goemaxima/
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 6

etc:
  mycnf: ""
  php: ""
  phpfpm: ""
  nginx: ""
  nginxSite: ""
  configphp: ""
  redisconf: ""

pvc:
  html:
    storageClassName: ""
    accessMode: ReadWriteOnce
    size: 1Gi
  moodledata:
    storageClassName: ""
    accessMode: ReadWriteOnce
    size: 1Gi
  mysql:
    storageClassName: ""
    accessMode: ReadWriteOnce
    size: 1Gi

global:
  existingPvc:
    html: ""
    moodledata: ""
    mysql: ""
  # TODO: upload to dockerhub 
  htmlImage: chungc/equiz_html
  phpfpminitImage: chungc/equiz_phpfpminit

secret:
  phpfpminit:
    ADMINPASS: &ADMINPASS 'Admin.123'
    DBPASS: &DBPASS 'yourpassword'
    UPGRADEKEY: ''
  mariadb:
    MYSQL_ROOT_PASSWORD: *DBPASS
    MYSQL_PASSWORD: *DBPASS

env:
  phpfpminit:
    ADMINUSER: admin
    DBUSER: &DBUSER moodleuser
    ADMINEMAIL: ''
    SUPPORTEMAIL: ''
    WWWROOT: 'http://localhost'
    DATAROOT: '/var/www/moodledata'
    DBTYPE: mariadb
    DBHOST: mariadb
    DBNAME: &DBNAME moodle
    DBPORT: '3306'
    DBSOCKET: '/var/run/mysqld/mysqld.sock'
    SITEPRESET: ''
    PREFIX: 'mdl_'
    FULLNAME: 'E-Quiz CS1302'
    SHORTNAME: cs1302
    SUMMARY: 'E-Quiz for CS1302 Introduction to Computer Programming.'
  mariadb:
    MYSQL_USER: *DBUSER
    MYSQL_DATABASE: *DBNAME