# namespace for the helm deployment
namespace ?= {{ namespace }}
# release name for the helm deployment
release ?= {{ release }}
# registry name to push docker images built for equiz
registry ?= {{ registry }}
# project name used for docker-compose and the prefix for images built for equiz such as html, phpfpminit, and phpfpm.
project ?= {{ namespace }}
tag ?= latest
# e-quiz helm chart
chart ?= ../chart

# Build and push docker images for equiz
push.%:
	@cd $*-docker && \
	make registry=$(registry) name=$(project)_$* tag=$(tag)

push: push.html push.phpfpm

# Create the namespace if it does not exist
namespace:
	@if ! kubectl get namespace $(namespace) >/dev/null 2>&1; then \
        echo "Creating namespace $(namespace)"; \
        kubectl create namespace $(namespace); \
    else \
        echo "Namespace $(namespace) already exists"; \
    fi

# Remove the namespace
# NOTE:
#   - Helm deployments and other resources created under the namespace will be removed.
rm.namespace:
	@if kubectl get namespace $(namespace) >/dev/null 2>&1; then \
		echo "Removing namespace $(namespace)..."; \
		kubectl delete namespace $(namespace); \
    fi

# Helm upgrade equiz
upgrade: namespace push
	@echo "Helm upgrading $(release) in $(namespace)..." && \
	microk8s helm upgrade -i -n $(namespace) $(release) ../chart -f values.yaml --wait

# Helm test upgrade
test:
	@echo "Helm test upgrading $(release) in $(namespace)..."
	microk8s helm upgrade -i -n $(namespace) $(release) ../chart -f values.yaml --wait --dry-run --debug

# Get the helm deployment and resources created
status:
	@helm list -n $(namespace) && kubectl get all -n $(namespace)

# Helm delete equiz
delete:
	@echo "Deleting $(release) from $(namespace)..."
	microk8s helm delete -n $(namespace) $(release) --wait

# Cleanup
# Remove docker-compose and helm deployments along with the persistent volume claims.
clean: rm.namespace
	@echo "Cleaning up..."

# Attach a shell to phpfpm container to run scripts as www-data user 
# to creating courses, install plugins, ...
# Files in attach/ will be attached to /attach/ in the container during the lifetime of the shell.
shell:
	@echo "Copying files to /attach in phpfpm..." && \
	kubectl cp --no-preserve=true -c phpfpm attach $(namespace)/phpfpm-0:/ && \
	echo "Attaching a shell to run scripts as www-data user" && \
	kubectl exec phpfpm-0 -it -n $(namespace) -c phpfpm -- /bin/bash /attach/init.sh


.PHONY: clean upgrade delete namespace test rm.% push.% push