apiVersion: v1
kind: Pod
metadata:
  name: clean-pvc
  namespace: equiz
spec:
  restartPolicy: Never
  containers:
  - name: cleaner
    image: busybox
    command: ["/bin/sh", "-c", "rm -rf /mnt/* /mnt/.[^.]* 2>/dev/null; echo 'Volume cleaned!'"]
    volumeMounts:
    - name: vol
      mountPath: /mnt
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: default-equiz-html
