apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "equiz.release" . }}-etc
  labels:
    {{- include "equiz.labels" . | nindent 4 }}
data:
  my.cnf: |-
    {{- if .Values.etc.mycnf }}
    {{- .Values.etc.mycnf | nindent 4 }}
    {{- else }}
    {{- .Files.Get "etc/my.cnf" | nindent 4 }}
    {{- end }}
  php-fpm.conf: |-
    {{- if .Values.etc.phpfpm }}
    {{- .Values.etc.phpfpm | nindent 4 }}
    {{- else }}
    {{- .Files.Get "etc/php-fpm.conf" | nindent 4 }}
    {{- end }}
  php.ini: |-
    {{- if .Values.etc.php }}
    {{- .Values.etc.php | nindent 4 }}
    {{- else }}
    {{- .Files.Get "etc/php.ini" | nindent 4 }}
    {{- end }}
  nginx.conf: |-
    {{- if .Values.etc.nginx }}
    {{- .Values.etc.nginx | nindent 4 }}
    {{- else }}
    {{- .Files.Get "etc/nginx.conf" | nindent 4 }}
    {{- end }}
  nginx-site.conf: |-
    {{- if .Values.etc.nginxSite }}
    {{- .Values.etc.nginxSite | nindent 4 }}
    {{- else }}
    {{- .Files.Get "etc/nginx-site.conf" | nindent 4 }}
    {{- end }}
  config.php: |-
    {{- if .Values.etc.configphp }}
    {{- .Values.etc.configphp | nindent 4 }}
    {{- else }}
    {{- .Files.Get "etc/config.php" | nindent 4 }}
    {{- end }}
  pool.conf: |-
    {{- if .Values.etc.poolconf }}
    {{- .Values.etc.poolconf | nindent 4 }}
    {{- else }}
    {{- .Files.Get "etc/pool.conf" | nindent 4 }}
    {{- end }}
  redis.conf: |-
    {{- if .Values.etc.redisconf }}
    {{- .Values.etc.redisconf | nindent 4 }}
    {{- else }}
    {{- .Files.Get "etc/redis.conf" | nindent 4 }}
    {{- end }}
  forcedcache.json: |-
    {{- if .Values.etc.forcedcachejson }}
    {{- .Values.etc.forcedcachejson | nindent 4 }}
    {{- else }}
    {{- .Files.Get "etc/forcedcache.json" | nindent 4 }}
    {{- end }}