apiVersion: v1
kind: Secret
metadata:
  name: {{ include "equiz.release" . }}-phpfpminit-secret
  labels:
    {{- include "equiz.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secret.phpfpminit }}
  {{- range $k, $v :=  .}}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "equiz.release" . }}-mariadb-secret
  labels:
    {{- include "equiz.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secret.mariadb }}
  {{- range $k, $v :=  .}}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
  {{- end }}