apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: myca-ss
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: myca
spec:
  ca:
    secretName: myca-key-pair