FROM php:8.1-fpm-alpine3.18 as prod

RUN apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        libzip-dev \
        libpng-dev \
        libxml2-dev \
        icu-dev \
        yaml-dev \
    && apk add --no-cache \
        libzip \
        libpng \
        libxml2 \
        icu \
        yaml \
    && printf "%s\n" "yes" | pecl install \
        xmlrpc-1.0.0RC3 \
        igbinary-3.2.14 \
        redis-5.3.7 \
        apcu-5.1.22 \
        yaml-2.2.3 \
    && docker-php-ext-install \
        # Enabled by default in the current php image
        # iconv \
        # mbstring \
        # curl \
        # openssl \
        # tokenizer \
        # ctype \
        # # some error
        # dom \
        # xml \
        # # core extensions, always available
        # pcre \
        # spl \
        # json \
        # # Deprecated
        # pdo_mysql \
        #
        # Required/recommended for moodle but not yet included by default
        exif \
        soap \
        zip \
        gd \
        simplexml \
        intl \
        # For mariadb
        mysqli \
        # Others
        # bcmath \
        opcache \
        -j $(nproc) \
    && docker-php-ext-enable \
        # required for extensions not installed with docker-php-ext-install
        xmlrpc \
        igbinary \
        redis \
        apcu \
        # for Moodle Stack
        yaml \
    && apk del .build-deps \
    && rm -rf /tmp/pear/*

# See https://github.com/tmuras/moosh
RUN url='https://moodle.org/plugins/download.php/29895/moosh_moodle42_2023090700.zip' \
    dir='/opt' \
    && tmp="/tmp/$(basename $url)" && wget -O $tmp $url && unzip -q -o $tmp -d $dir && rm $tmp \
    && chown -R www-data:www-data "$dir/moosh" && ln -s "$dir/moosh/moosh.php" "/usr/local/bin/moosh"

FROM prod as init

COPY --chmod=755 sbin/ /usr/local/sbin/

ENV WWWROOT='http://localhost' \
    DATAROOT=/var/www/moodledata \
    DBTYPE=mariadb \
    DBHOST=localhost \
    DBNAME=moodle \
    DBUSER=moodleuser \
    DBPASS='yourpassword' \
    DBPORT=3306 \
    DBSOCKET='/var/run/mysqld/mysqld.sock' \
    SITEPRESET='' \
    PREFIX='mdl_' \
    FULLNAME='E-Quiz CS1302' \
    SHORTNAME=cs1302 \
    SUMMARY='E-Quiz for CS1302 Introduction to Computer Programming.' \
    ADMINUSER=admin \
    ADMINPASS='Admin.123' \
    ADMINEMAIL='' \
    SUPPORTEMAIL='' \
    UPGRADEKEY=''

ENTRYPOINT []

CMD ["run.sh"]

{# FROM init as debugger

USER root

RUN apk add --no-cache --virtual .build-deps \
     linux-headers $PHPIZE_DEPS \
    && pecl install \
        xdebug-3.2.1 \
    && docker-php-ext-enable \
        xdebug \
    && apk del .build-deps \
    && rm -rf /tmp/pear/* #}
{# 
### code-server ###
RUN wget -q https://code-server.dev/install.sh -O /tmp/install.sh && \
    sh /tmp/install.sh --version 4.14.1 && \
    code-server --extensions-dir /usr/lib/code-server/lib/vscode/extensions \
        --install-extension ms-python.python && \
    rm -rf ~/.cache/code-server/ && \
    rm -rf /tmp/install.sh

ENV XDEBUG_MODE='debug' XDEBUG_CONFIG='client_port=9003'


# Configurations
COPY etc/ /tmp/etc/

RUN \
    # Set up Nginx configuration
    mv /tmp/etc/nginx.conf /etc/nginx/nginx.conf \
    && mv /tmp/etc/nginx-site.conf /etc/nginx/sites-available/default \
    # Set up PHP-FPM configuration
    && mv /tmp/etc/php-fpm.conf /usr/local/etc/php-fpm.d/zzz-custom.conf \
    # Set up PHP configuration
    && mv /tmp/etc/php.ini /usr/local/etc/php/php.ini \
    && mv /tmp/etc/debug-custom.ini /usr/local/etc/php/conf.d/debug-custom.ini \
    # Set up Mariadb configuration
    && mv /tmp/etc/my.cnf /etc/mysql/my.cnf \
    # See scenario 4 in this tracker: https://tracker.moodle.org/browse/MDL-73145
    && rm -rf /tmp/etc

CMD ["sh"]

# code-server
EXPOSE 8080
 #}
