FROM php:8.3-fpm-alpine3.23 AS prod

RUN apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        libzip-dev \
        libpng-dev \
        libxml2-dev \
        icu-dev \
        yaml-dev \
    && apk add --no-cache \
        libzip \
        libpng \
        libxml2 \
        icu \
        yaml \
    && printf "%s\n" "yes" | pecl install \
        xmlrpc-1.0.0RC3 \
		igbinary-3.2.16 \
        redis-6.1.0 \
        apcu-5.1.28 \
        yaml-2.3.0 \
	&& mkdir -p /tmp/xmlrpc \
    && curl -fsSL https://github.com/php/pecl-networking-xmlrpc/archive/refs/heads/master.tar.gz | tar xz -C /tmp/xmlrpc --strip-components=1 \
    && cd /tmp/xmlrpc \
    && phpize \
    && ./configure \
    && make \
    && make install \
    && cd / \
    && rm -rf /tmp/xmlrpc \
    && docker-php-ext-install \
        # Enabled by default in the current php image
        # iconv \
        # mbstring \
        # curl \
        # openssl \
        # tokenizer \
        # ctype \
        # # some error
        # dom \
        # xml \
        # # core extensions, always available
        # pcre \
        # spl \
        # json \
        # # Deprecated
        # pdo_mysql \
        #
        # Required/recommended for moodle but not yet included by default
        exif \
        soap \
        zip \
        gd \
        simplexml \
        intl \
        # For mariadb
        mysqli \
        # Others
        # bcmath \
        opcache \
        -j $(nproc) \
    && docker-php-ext-enable \
        # required for extensions not installed with docker-php-ext-install
        xmlrpc \
        igbinary \
        redis \
        apcu \
        # for Moodle Stack
        yaml \
    && apk del .build-deps \
    && rm -rf /tmp/pear/*


RUN apk add --no-cache bash git openssh-client && \
    # See https://moodle.org/plugins/pluginversions.php?id=522
    #     https://github.com/tmuras/moosh/tags
    # moodle.org blocks wget/curl with 403 (Cloudflare). Use GitHub release instead.
    url='https://github.com/tmuras/moosh/archive/refs/tags/1.27.tar.gz' \
    dir='/opt' \
    && tmp="/tmp/moosh.tgz" && wget -O $tmp $url \
    && mkdir -p /tmp/moosh-src && tar xzf $tmp -C /tmp/moosh-src --strip-components=1 && rm $tmp \
    && mv /tmp/moosh-src "$dir/moosh" && rm -rf /tmp/moosh-src \
    && chown -R www-data:www-data "$dir/moosh" && ln -s "$dir/moosh/moosh.php" "/usr/local/bin/moosh" \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && cd "$dir/moosh" && composer install --no-dev --no-interaction --ignore-platform-reqs \
    && chown -R www-data:www-data "$dir/moosh/vendor"

FROM prod AS init

COPY --chmod=755 sbin/ /usr/local/sbin/

ENV WWWROOT='http://localhost' \
    DATAROOT=/var/www/moodledata \
    DBTYPE=mariadb \
    DBHOST=localhost \
    DBNAME=moodle \
    DBUSER=moodleuser \
    DBPASS='yourpassword' \
    DBPORT=3306 \
    DBSOCKET='/var/run/mysqld/mysqld.sock' \
    SITEPRESET='' \
    PREFIX='mdl_' \
    FULLNAME='E-Quiz CS1302' \
    SHORTNAME=cs1302 \
    SUMMARY='E-Quiz for CS1302 Introduction to Computer Programming.' \
    ADMINUSER=admin \
    ADMINPASS='Admin.123' \
    ADMINEMAIL='' \
    SUPPORTEMAIL='' \
    UPGRADEKEY=''

ENTRYPOINT []

CMD ["run.sh"]

{# FROM init AS debugger

USER root

RUN apk add --no-cache --virtual .build-deps \
     linux-headers $PHPIZE_DEPS \
    && pecl install \
        xdebug-3.2.1 \
    && docker-php-ext-enable \
        xdebug \
    && apk del .build-deps \
    && rm -rf /tmp/pear/* #}
{# 
### code-server ###
RUN wget -q https://code-server.dev/install.sh -O /tmp/install.sh && \
    sh /tmp/install.sh --version 4.14.1 && \
    code-server --extensions-dir /usr/lib/code-server/lib/vscode/extensions \
        --install-extension ms-python.python && \
    rm -rf ~/.cache/code-server/ && \
    rm -rf /tmp/install.sh

ENV XDEBUG_MODE='debug' XDEBUG_CONFIG='client_port=9003'


# Configurations
COPY etc/ /tmp/etc/

RUN \
    # Set up Nginx configuration
    mv /tmp/etc/nginx.conf /etc/nginx/nginx.conf \
    && mv /tmp/etc/nginx-site.conf /etc/nginx/sites-available/default \
    # Set up PHP-FPM configuration
    && mv /tmp/etc/php-fpm.conf /usr/local/etc/php-fpm.d/zzz-custom.conf \
    # Set up PHP configuration
    && mv /tmp/etc/php.ini /usr/local/etc/php/php.ini \
    && mv /tmp/etc/debug-custom.ini /usr/local/etc/php/conf.d/debug-custom.ini \
    # Set up Mariadb configuration
    && mv /tmp/etc/my.cnf /etc/mysql/my.cnf \
    # See scenario 4 in this tracker: https://tracker.moodle.org/browse/MDL-73145
    && rm -rf /tmp/etc

CMD ["sh"]

# code-server
EXPOSE 8080
 #}
