apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
data:
  mysql_user: {{ .Values.credentials.MYSQL_USER | quote }}
  mysql_database: {{ .Values.credentials.MYSQL_DATABASE | quote }}