{{- if .Values.credentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_PWD: {{ .Values.credentials.MYSQL_PWD | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.credentials.MYSQL_PASSWORD | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.credentials.MYSQL_ROOT_PASSWORD | b64enc | quote }}
{{- end }}