apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myca
  namespace: cert-manager
spec:
  isCA: true
  commonName: myca
  secretName: myca-key-pair
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: myca-ss-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  subject:
    organizations: 
      - myorg