apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: myca-ss-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: myca-issuer
spec:
  ca:
    secretName: myca-key-pair